// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using OrbitalGuard.API.Data;

#nullable disable

namespace OrbitalGuard.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609032128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrbitalGuard.API.Models.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<DateTime>("DtHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_HORA");

                    b.Property<int>("IdRegiao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<double?>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LATITUDE");

                    b.Property<double?>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NIVEL");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TIPO");

                    b.HasKey("IdAlerta");

                    b.HasIndex("IdRegiao");

                    b.ToTable("TB_ALERTA");
                });

            modelBuilder.Entity("OrbitalGuard.API.Models.Notificacao", b =>
                {
                    b.Property<int>("IdNotificacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_NOTIFICACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacao"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("CANAL");

                    b.Property<DateTime?>("DtEnvio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ENVIO");

                    b.Property<bool>("Enviada")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ENVIADA");

                    b.Property<int>("IdAlerta")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MENSAGEM");

                    b.HasKey("IdNotificacao");

                    b.HasIndex("IdAlerta");

                    b.HasIndex("IdUsuario");

                    b.ToTable("TB_NOTIFICACAO");
                });

            modelBuilder.Entity("OrbitalGuard.API.Models.Regiao", b =>
                {
                    b.Property<int>("IdRegiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegiao"));

                    b.Property<decimal?>("AreaKm2")
                        .HasPrecision(12, 2)
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("AREA_KM2");

                    b.Property<string>("Bioma")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("BIOMA");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("ESTADO");

                    b.Property<double?>("Latitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LATITUDE");

                    b.Property<double?>("Longitude")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("NmRegiao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_REGIAO");

                    b.Property<string>("RiscoNivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("RISCO_NIVEL");

                    b.HasKey("IdRegiao");

                    b.HasIndex("NmRegiao", "Estado")
                        .IsUnique();

                    b.ToTable("TB_REGIAO");
                });

            modelBuilder.Entity("OrbitalGuard.API.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DtCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("NmUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("NM_USUARIO");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("PERFIL");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("SENHA_HASH");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("TB_USUARIO");
                });

            modelBuilder.Entity("OrbitalGuard.API.Models.UsuarioRegiao", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.Property<int>("IdRegiao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    b.Property<DateTime>("DtInscricao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_INSCRICAO");

                    b.HasKey("IdUsuario", "IdRegiao");

                    b.HasIndex("IdRegiao");

                    b.ToTable("TB_USUARIO_REGIAO");
                });

            modelBuilder.Entity("OrbitalGuard.API.Models.Alerta", b =>
                {
                    b.HasOne("OrbitalGuard.API.Models.Regiao", "Regiao")
                        .WithMany("Alertas")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("OrbitalGuard.API.Models.Notificacao", b =>
                {
                    b.HasOne("OrbitalGuard.API.Models.Alerta", "Alerta")
                        .WithMany("Notificacoes")
                        .HasForeignKey("IdAlerta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrbitalGuard.API.Models.Usuario", "Usuario")
                        .WithMany("Notificacoes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alerta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OrbitalGuard.API.Models.UsuarioRegiao", b =>
                {
                    b.HasOne("OrbitalGuard.API.Models.Regiao", "Regiao")
                        .WithMany("UsuariosMonitorando")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrbitalGuard.API.Models.Usuario", "Usuario")
                        .WithMany("RegioesMonitoradas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("OrbitalGuard.API.Models.Alerta", b =>
                {
                    b.Navigation("Notificacoes");
                });

            modelBuilder.Entity("OrbitalGuard.API.Models.Regiao", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("UsuariosMonitorando");
                });

            modelBuilder.Entity("OrbitalGuard.API.Models.Usuario", b =>
                {
                    b.Navigation("Notificacoes");

                    b.Navigation("RegioesMonitoradas");
                });
#pragma warning restore 612, 618
        }
    }
}
