
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
    FROM dba_users
   WHERE username = 'ORBITAL_USER';

  IF v_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP USER orbital_user CASCADE';
  END IF;
END;
/


CREATE USER orbital_user IDENTIFIED BY "OrbitalPwd123";


GRANT CONNECT, RESOURCE TO orbital_user;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE TO orbital_user;


ALTER USER orbital_user QUOTA UNLIMITED ON USERS;
ALTER USER orbital_user DEFAULT TABLESPACE USERS;

EXIT;