ALTER SESSION SET CONTAINER = XEPDB1;

GRANT CONNECT, RESOURCE TO ORBITAL_USER;
GRANT CREATE SESSION    TO ORBITAL_USER;
GRANT CREATE TABLE      TO ORBITAL_USER;
GRANT CREATE SEQUENCE   TO ORBITAL_USER;
GRANT CREATE VIEW       TO ORBITAL_USER;
GRANT CREATE PROCEDURE  TO ORBITAL_USER;

ALTER USER ORBITAL_USER QUOTA UNLIMITED ON USERS;
ALTER USER ORBITAL_USER DEFAULT TABLESPACE USERS;

EXIT;